feat: Todo CRUD 기능 구현
SsafyBox/sandbox pull request #8
Opened 2024-10-23 06:19 UTC by chan0518

### ✏️ 완료한 기능 명세

**초기 설정**
WebConfig Class를 활용하여 CORS해결
MySQL, Lombok 의존성 설정

**CRUD API 구현**
- Create : POST
- Read : GET
- Update : PATCH
- Delete : DELETE

**구조 설명**
- MVC패턴을 적용
- Controller로 각 CRUD에 대해 Service로 처리를 하며 Service에서 Dao를 활용하여 DB에 접근

2024-10-23 10:41 UTC, 8resd8 commented on src/main/java/com/ssafy/ssafybox/controller/SsafyBoxController.java
> +        HashMap<String, List<TodoDto>> hm = new HashMap<>();
hm.. 변수명이 아쉽다!

2024-10-23 10:42 UTC, 8resd8 commented on src/main/java/com/ssafy/ssafybox/model/dto/TodoDto.java
> +@Getter
DB값을 조회하는건 Read만 가능하게 하는게 더 안전할 것같은데 Setter 있어도 괜찮을까요?

2024-10-23 10:45 UTC, 8resd8 commented on src/main/java/com/ssafy/ssafybox/model/dao/SsafyboxDaoImpl.java
> +        Connection c = null;
변수명이.. ㅜㅜ 반복되는 중복코드들이 많은데 myBatis나 JDBC template, JPA의 도움을 받으면 줄일 수 있어요!

2024-10-23 10:46 UTC, 8resd8 reviewed
이 클래스를 현재 사용하고 있나요?

2024-10-23 11:02 UTC, 8resd8 commented on src/main/java/com/ssafy/ssafybox/SsafyboxApplication.java
> +		System.out.println("정상적으로 서버가 실행되었습니다.");
System.out 대신 이제 로그를 남기는 방법! @Slf4j 라는 좋은 것은 어떨까요?

2024-10-24 05:26 UTC, shunny822 reviewed
수고하였습니다! interface도 사용하고 구조가 잘 짜여진 것 같아요 👍
이제 수업에서 MyBatis도 배웠으니까 JDBC는 놓아주고 MyBatis나 JPA를 사용해보는 것도 좋을 것 같습니닷. 어차피 관통에서 써야하니깐요~

2024-10-24 05:26 UTC, shunny822 commented on src/main/java/com/ssafy/ssafybox/model/dto/RequestDto.java
> +    }
content는 어차피 null이 허용되지 않는데 request dto의 생성자를 2개 만든 이유가 있나요? 오버로딩을 목적으로 한거라면, API 각각의 request dto를 따로 두는 것을 추천드립니다. API가 많아지면 하나의 request dto만으로 데이터를 받을 수 없으니까요~

추가로 request dto는 요청 데이터의 검증 역할도 하기 때문에 null을 허용하지 않도록 하는 방법을 찾아서 적용하면 좋을 것 같습니다.

2024-10-24 05:26 UTC, shunny822 commented on src/main/java/com/ssafy/ssafybox/model/dto/ResponseDto.java
> +    }
response dto도 request dto와 같은 맥락인데 하나의 class안에서 오버로딩하는 것 보다 `MessageResponse`, `TodoListResponse` 등.. (naming은 어떤 것을 위한 dto인지 알 수 있도록) 나누는 것이 어떨까요?

2024-10-24 05:26 UTC, shunny822 commented on src/main/java/com/ssafy/ssafybox/util/DBUtil.java
> +    private static final String URL = "jdbc:mysql://127.0.0.1:3307/ssafybox?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8";
포트번호 3307로 한 이유가 있나요?ㅋㅋㅋ

2024-10-24 05:32 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/SsafyboxApplication.java
> +		System.out.println("정상적으로 서버가 실행되었습니다.");
@SLF4J 기능을 모르고 있어서 사용하지 못했습니다. 앞으로는 System.out을 사용하는대신 @SLF4J를 사용하도록 하겠습니다! 좋은 정보 감사합니다

2024-10-24 05:33 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/controller/SsafyBoxController.java
> +        HashMap<String, List<TodoDto>> hm = new HashMap<>();
코딩테스트를 진행할 때의 버릇으로 자료구조가 뭔지 파악하기 쉽게 앞글자씩 따서 변수명을 지정하였습니다. 
앞으로 기능구현을 할 때는 어떤 자료를 담는지 생각하며 변수명을 적도록 하겠습니다.

2024-10-24 05:35 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/model/dao/SsafyboxDaoImpl.java
> +        Connection c = null;
현재 제가 알고 있는 지식으로 DBUtil을 사용하여 Dao를 통해 DB에 접근 하는 방법만 알고 있었기에 이렇게 사용하였습니다. myBatis나  JDBC template, JPA을 공부하여 적용시켜보겠습니다.

2024-10-24 05:46 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/model/dto/RequestDto.java
> +    }
기본 생성자는 반드시 필요하다고 생각하여 작성했으나, 지금 보니 잘못된 코드임을 알게 되었습니다. 
소중한 피드백 감사드리며, 말씀해주신 내용을 반영하도록 하겠습니다.

2024-10-24 05:48 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/model/dto/TodoDto.java
> +@Getter
좋은 피드백 감사드립니다. DB데이터에 대해선 Setter를 사용할 수 없도록 수정하겠습니다.

2024-10-24 05:48 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/util/DBUtil.java
> +    private static final String URL = "jdbc:mysql://127.0.0.1:3307/ssafybox?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8";
제 맥북에 3306포트로 mysql이 접근이 불가능하여 doker를 사용하여 포트번호를 변경하여 사용하고 있었습니다.

2024-10-24 06:17 UTC, lizuAg requested changes

2024-10-24 06:17 UTC, lizuAg commented on src/main/java/com/ssafy/ssafybox/util/DBUtil.java
> +    private static final String PASSWORD = "ssafy";
application.properties에서 찾을 수 있는 값들이네요 ! @value 어노테이션을 사용해서 값들을 읽어들일 수 있을 것 같아요 ~

2024-10-24 06:17 UTC, lizuAg commented on src/main/java/com/ssafy/ssafybox/util/DBUtil.java
> +    private static final String PASSWORD = "ssafy";
... 당신의 데이터베이스는 털렸다. 내일 아침까지 500만원을 준비해라 🔫🔫

2024-10-24 06:17 UTC, lizuAg commented on src/main/java/com/ssafy/ssafybox/model/dto/TodoDto.java
> +    }
@Getter 어노테이션 사용하는데, 직접 정의한 getter가 필요할까요 ?? 🤔

2024-10-24 06:17 UTC, lizuAg commented on src/main/java/com/ssafy/ssafybox/model/dto/TodoDto.java
> +    }
boolean 대신 Boolean을 사용하신 이유가 있을까요? 만약에 completed에 null이 들어가면 어떻게 되나요 ?

2024-10-24 06:54 UTC, dynamite885 commented on .gitignore
> +.idea/**/usage.statistics.xml
ㅣㅢㅡㅏㅣ

2024-10-24 07:20 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/model/dto/TodoDto.java
> +    }
getter를 사용했음에도 completed만 getter메서드를 쓸 수가 없어 직접 만들어서 사용하였습니다. 왜 getter어노테이션을 사용했는데 안됬는지 아직 이유를 찾지 못했습니다.

boolean 대신 Boolean을 사용한 까닭은 혹시나 null값이 왔을 경우 프리미티브타입이라면 오류가 생기지만 레퍼런스타입을 사용한다면 null일 경우 참조를 하지 않는다는 뜻이 되어 오류를 발생시키지 않습니다

2024-10-24 07:24 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/util/DBUtil.java
> +    private static final String PASSWORD = "ssafy";
😭😭 500만원을 지키기 위해서 빨리 민감정보를 숨겨야겠네요! 
@value 어노테이션을 사용해서 값들을 읽을 수 있도록 하겠습니다.😤

2024-10-24 07:27 UTC, chan0518 commented on src/main/java/com/ssafy/ssafybox/model/dto/ResponseDto.java
> +    }
지금 생각해보니 두 가지로 나누거나 빌더패턴을 사용한다면 더 좋을것 같다는 생각이 드네요!! 피드백 감사합니다!!😊😊

2024-10-24 11:05 UTC, lizuAg commented on src/main/java/com/ssafy/ssafybox/model/dto/TodoDto.java
> +    }
작성하신 생성자에는 boolean이 들어오고 있는데 설명하신 것과 다른 것 같습니다. 엔티티 클래스에 원시타입과 참조타입을 결정하는 기준은 null이 허용되는 컬럼인지, 아닌지라고 생각합니다.

원시타입에 null이 할당될 수 없는 것은 맞습니다. 하지만 원시타입에 null을 할당하는 로직은 컴파일 단계 전에도 쉽게 찾을 수 있습니다. null이 할당되면 안되는 컬럼에 null을 할당하는 케이스는 검증로직을 추가하여 해결해야합니다.

2024-10-24 11:24 UTC, 8resd8 approved these changes

2024-10-24 11:28 UTC, shunny822 approved these changes

2024-10-24 11:41 UTC, lizuAg approved these changes

2024-10-24 12:23 UTC, HoberMin commented on src/main/java/com/ssafy/ssafybox/controller/SsafyBoxController.java
> +        HashMap<String, List<TodoDto>> hm = new HashMap<>();
@8resd8 리뷰는 존댓말로 남겨야합니다. 
아쉽다. 에서 끝나는것은 비난이고 다른 변수명을 제안하거나 왜 아쉬운지에 대한 이유를 포함해줘야 리뷰가 됩니다.

2024-10-24 12:27 UTC, HoberMin commented on src/main/java/com/ssafy/ssafybox/model/dao/SsafyboxDaoImpl.java
> +        Connection c = null;
현재 `알고있는 지식의 한계에서 여기까지 구현했다` 보다는, DBUtil을 활용했을 때만의 장점을 찾아보는건 어떨까요 ? 
JPA와 myBatis보다 더 나은 순간이 없지 않을 것 으로 예상됩니다.

2024-10-24 12:27 UTC, HoberMin commented
> 이 클래스를 현재 사용하고 있나요?

태그를 부탁드립니다.

2024-10-27 10:04 UTC, dynamite885 approved these changes

2024-10-27 10:04 UTC, dynamite885 commented on src/main/java/com/ssafy/ssafybox/model/dao/SsafyboxDaoImpl.java
> +    }
```suggestion
    public Long createTodo(String content) throws SQLException {
        Long id = -1;
        Connection c = null;
        PreparedStatement p = null;
        ResultSet rs = null;

        try {
            c = DBUtil.getConnection();
            String query = "INSERT INTO todos (content, completed) VALUES (?, false)";
            p = c.prepareStatement(query);
            p.setString(1, content);
            p.executeUpdate();
            
            rs = p.getGeneratedKeys();
            if (rs.next()) {
                id = rs.getInt("id");
            }
        } finally {
            DBUtil.close(rs, p,c);
        }
        return id;
    }
```
참고: https://narup.tistory.com/82

insert문 실행 시 auto_increment로 자동 생성되는 id 값 가져오는 방법입니다.

2024-10-28 12:43 UTC, merged